# Generated by Django 6.1.1 on 2026-09-06 01:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft — not connected to Printful'), ('hidden', 'Hidden — staged, not public'), ('live', 'Live')], default='hidden', max_length=10)),
                ('is_base', models.BooleanField(default=False)),
                ('go_live_at', models.DateTimeField(blank=True, null=True)),
                ('theme_tokens', models.JSONField(blank=True, default=dict)),
                ('scene_asset', models.ImageField(blank=True, null=True, upload_to='collections/')),
                ('entry_object', models.CharField(blank=True, max_length=120)),
                ('motion_preset', models.CharField(blank=True, max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_base', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('story', models.TextField(blank=True, help_text='The short narrative shown on the card.')),
                ('artwork', models.ImageField(blank=True, help_text='Print-ready file. Empty until the real art is dropped in.', null=True, upload_to='designs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('product_type', models.CharField(choices=[('tee', 'T-shirt'), ('sticker', 'Sticker'), ('sweatshirt', 'Sweatshirt'), ('mug', 'Mug')], max_length=12)),
                ('base_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('shipping_est', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('default_sizes', models.JSONField(blank=True, default=list)),
                ('printful_blueprint_id', models.CharField(blank=True, max_length=40)),
                ('printful_provider_id', models.CharField(blank=True, max_length=40)),
                ('print_placement', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('tee', 'T-shirt'), ('sticker', 'Sticker'), ('sweatshirt', 'Sweatshirt'), ('mug', 'Mug')], max_length=12)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft — not connected to Printful'), ('hidden', 'Hidden — staged, not public'), ('live', 'Live')], default='draft', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('base_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('shipping_est', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('printful_product_id', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='shop.collection')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='shop.design')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='shop.producttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'design__title'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('kind', models.CharField(choices=[('mockup', 'Mockup'), ('lifestyle', 'Lifestyle'), ('detail', 'Print detail')], default='mockup', max_length=12)),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16)),
                ('width_in', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('height_in', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('printful_variant_id', models.CharField(blank=True, max_length=40)),
                ('in_stock', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='designs', to='shop.tag'),
        ),
    ]
