# Generated by Django 6.1.1 on 2026-09-06 01:46

import django.db.models.deletion
import shop.orders
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('items_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('pending_approval', 'Awaiting approval'), ('approved', 'Approved'), ('submitted', 'Submitted to partner'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_approval', max_length=20)),
                ('track_token', models.CharField(default=shop.orders._token, editable=False, max_length=40, unique=True)),
                ('curator_note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(default=shop.orders._token, editable=False, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_title', models.CharField(max_length=160)),
                ('product_type', models.CharField(max_length=12)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('size_label', models.CharField(blank=True, max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unit_supplier_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.listing')),
                ('listing_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.listingsize')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='printful', max_length=40)),
                ('partner_order_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('problem', 'Problem — needs attention')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('tracking_url', models.URLField(blank=True)),
                ('carrier', models.CharField(blank=True, max_length=60)),
                ('problem_note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='shop.order')),
                ('items', models.ManyToManyField(blank=True, related_name='fulfillments', to='shop.orderitem')),
            ],
        ),
    ]
