# Generated by Django 6.1.1 on 2026-09-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_subscriber_orderitem_fulfillment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverheadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incurred_on', models.DateField()),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.CharField(choices=[('hosting', 'Hosting & infrastructure'), ('software', 'Software & services'), ('marketing', 'Marketing & ads'), ('supplies', 'Supplies & samples'), ('fees', 'Fees & charges'), ('other', 'Other')], default='other', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-incurred_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='competitor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hand-entered, for the pricing workspace.', max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='shop.order')),
            ],
            options={
                'ordering': ['handled', '-created'],
            },
        ),
    ]
