# Generated by Django 6.1.1 on 2026-09-19 18:12

import shop.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_page_visitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='artwork',
            field=models.FileField(blank=True, help_text='Print-ready original (SVG or PNG). Private: viewable only in the console.', null=True, storage=shop.storage.get_private_storage, upload_to='designs/'),
        ),
    ]
