# Generated by Django 6.1.1 on 2026-09-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_design_artwork_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured_on_landing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='landing_sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
