# Generated by Django 6.1.1 on 2026-09-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_collection_landing_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='printful_blueprint_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
