# Generated by Django 6.1.1 on 2026-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_template_printful_blueprint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='print_position',
            field=models.CharField(choices=[('center', 'Centered'), ('higher', 'Higher'), ('lower', 'Lower'), ('left', 'Toward the left'), ('right', 'Toward the right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='print_scale_pct',
            field=models.PositiveSmallIntegerField(default=100, help_text='How large the print runs within its placement area (25-100%).'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='print_placement',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('back', 'Back'), ('left_chest', 'Left chest'), ('left_sleeve', 'Left sleeve'), ('right_sleeve', 'Right sleeve')], default='front', max_length=40),
        ),
    ]
