# Generated by Django 6.1.1 on 2026-09-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_listing_print_positioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='print_placement',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('back', 'Back'), ('left_chest', 'Left chest'), ('left_sleeve', 'Left sleeve'), ('right_sleeve', 'Right sleeve')], default='', help_text="Where the print goes. Blank uses the template's placement.", max_length=40),
        ),
    ]
