# Generated by Django 6.1.1 on 2026-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_listing_print_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('problem', 'Problem — needs attention'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
