# Generated by Django 6.1.1 on 2026-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_fulfillment_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='printful_sent_blueprint_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='listing',
            name='printful_sent_color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='listing',
            name='printful_sent_placement',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='listingsize',
            name='printful_catalog_variant_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
