# Generated by Django 6.1.1 on 2026-10-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_move_unsent_variant_ids_to_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='printful_sent_prints',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='print_position',
            field=models.CharField(choices=[('center', 'Centered'), ('higher', 'Higher'), ('lower', 'Lower'), ('left', 'Toward the left'), ('right', 'Toward the right'), ('top_left', 'Upper left'), ('top_right', 'Upper right')], default='center', max_length=10),
        ),
        migrations.CreateModel(
            name='ListingPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left_chest', 'Left chest'), ('left_sleeve', 'Left sleeve'), ('right_sleeve', 'Right sleeve')], max_length=40)),
                ('scale_pct', models.PositiveSmallIntegerField(default=100, help_text='How large the print runs within its placement area (25-100%).')),
                ('position', models.CharField(choices=[('center', 'Centered'), ('higher', 'Higher'), ('lower', 'Lower'), ('left', 'Toward the left'), ('right', 'Toward the right'), ('top_left', 'Upper left'), ('top_right', 'Upper right')], default='center', max_length=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('design', models.ForeignKey(blank=True, help_text="Blank = the same artwork as the listing's main print.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_as_extra_print', to='shop.design')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='shop.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'placement'), name='one_extra_print_per_placement')],
            },
        ),
    ]
