# Generated by Django 6.1.1 on 2026-10-10 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_multi_print_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('kind', models.CharField(choices=[('password', 'Password'), ('otp', 'Second-factor code')], default='password', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['username', 'created_at'], name='shop_failed_usernam_f68282_idx'), models.Index(fields=['ip', 'created_at'], name='shop_failed_ip_194c6d_idx'), models.Index(fields=['created_at'], name='shop_failed_created_95ac1f_idx')],
            },
        ),
    ]
