# Generated by Django 6.1.1 on 2026-10-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_failedlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='supplier_cost_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='supplier_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
