# Generated by Django 6.1.1 on 2026-10-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_fulfillment_supplier_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='ip_checked_on',
            field=models.DateField(blank=True, help_text='When trademark/copyright conflicts were last searched for.', null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='ip_notes',
            field=models.TextField(blank=True, help_text='Source files, licence terms, receipts, what was searched and what turned up.'),
        ),
        migrations.AddField(
            model_name='design',
            name='origin',
            field=models.CharField(choices=[('unknown', 'Not recorded yet'), ('original', 'Original work (I made it)'), ('commissioned', 'Commissioned (with a written assignment)'), ('licensed', 'Licensed (stock, marketplace or font licence)'), ('public_domain', 'Public-domain source'), ('ai', 'AI-assisted or generated'), ('other', 'Other (explain in the notes)')], default='unknown', max_length=16),
        ),
    ]
