# Generated by Django 6.1.1 on 2026-10-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_design_rights_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='printful_preview',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='printful_preview_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
